export const DATABASE_CONSTANTS = {
  MAX_CONNECTIONS: 50,
  IDLE_TIMEOUT: 1800000,
  WRITE_MAX_CONNECTIONS: 15,
  READ_MAX_CONNECTIONS: 25,
  WRITE_POOL_TIMEOUT: 30,
  READ_POOL_TIMEOUT: 20,
  CONNECT_TIMEOUT: 10,
  SOCKET_TIMEOUT: 0,
} as const;
