export const ENV_KEYS = {
  MASTER_DATABASE_WRITE_URL: 'MASTER_DATABASE_WRITE_URL',
  MASTER_DATABASE_READ_URL: 'MASTER_DATABASE_READ_URL',
  DATABASE_WRITE_URL: 'DATABASE_WRITE_URL',
  DATABASE_READ_URL: 'DATABASE_READ_URL',
  NODE_ENV: 'NODE_ENV',
} as const;
